<?php

function acf_featured_buttons()
{

    return array(
        array(
            'key' => 'field_65b819da1bed0',
            'label' => 'Featured Buttons',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_65b81aac1bed6',
            'label' => 'Add gap between buttons',
            'name' => 'featured_buttons_gap',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui_on_text' => 'Yes',
            'ui_off_text' => 'No',
            'ui' => 1,
        ),
        array(
            'key' => 'field_65b81aac1bed61',
            'label' => 'Add inner border',
            'name' => 'featured_buttons_inner_border',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65b81aac1bed6',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => 'Yes',
            'ui_off_text' => 'No',
            'ui' => 1,
        ),
        array(
            'key' => 'field_65b819e31bed1',
            'label' => 'Buttons',
            'name' => 'featured_buttons',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'table',
            'pagination' => 0,
            'min' => 2,
            'max' => 4,
            'collapsed' => 'field_65b81a041bed2',
            'button_label' => 'Add Button',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_65b81a041bed2',
                    'label' => 'Link',
                    'name' => 'link',
                    'aria-label' => '',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'parent_repeater' => 'field_65b819e31bed1',
                ),
                array(
                    'key' => 'field_65b81a151bed3',
                    'label' => 'Icon',
                    'name' => 'icon',
                    'aria-label' => '',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'icon_sets' => array(
                        0 => 'solid',
                        1 => 'regular',
                        2 => 'brands',
                    ),
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 0,
                    'show_preview' => 1,
                    'enqueue_fa' => 0,
                    'fa_live_preview' => '',
                    'choices' => array(),
                    'parent_repeater' => 'field_65b819e31bed1',
                ),
                array(
                    'key' => 'field_65b81a1d1bed4',
                    'label' => 'Background Color',
                    'name' => 'background_color',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'var(--clr-primary)' => 'Primary',
                        'var(--clr-secondary)' => 'Secondary',
                        'var(--clr-tertiary)' => 'Tertiary',
                        'var(--clr-quaternary)' => 'Quaternary',
                        'black' => 'Black',
                        'white' => 'White',
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_65b819e31bed1',
                ),
                array(
                    'key' => 'field_65b81a671bed5',
                    'label' => 'Hover Image',
                    'name' => 'hover_image',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'parent_repeater' => 'field_65b819e31bed1',
                ),
            ),
        ),
    );
}
