<?php

function acf_mass_times()
{
    return array(
        array(
            'key' => 'field_65b947300ad11',
            'label' => 'Parish Cluster Mass/Mission',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_65b9475c0ad14',
            'label' => 'Headline',
            'name' => 'mass_times_headline_1',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*Max 20 characters',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '20',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'parent_repeater' => 'field_61a917aeb95ez',
        ),
        array(
            'key' => 'field_65dcfeed09c98',
            'label' => 'Background Image',
            'name' => 'mass_times_bg_img',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '21',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'dove' => 'Dove',
                'lamb' => 'Lamb',
                'hand' => 'Hand',
                'select' => 'Select ->',
            ),
            'default_value' => "dove",
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 1,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6182f5a5311cz',
            'label' => 'Watermark Upload',
            'name' => 'watermark_upload',
            'type' => 'file',
            'instructions' => 'Recommended size 750x750.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65dcfeed09c98',
                        'operator' => '==',
                        'value' => 'select',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '21',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
		array(
			'key' => 'field_61a917aeb95ez',
			'label' => 'Parishes',
			'name' => 'parishes',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '*Min. 2, Max. 7',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 2,
			'max' => 7,
			'collapsed' => 'field_65b9475c0ad14',
			'button_label' => 'Add Parish',
			'rows_per_page' => 20,
			'sub_fields' => array(
                array(
                    'key' => 'field_65b9473e0ad12',
                    'label' => 'Image 1',
                    'name' => 'mass_times_image_1',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65b947580ad13',
                    'label' => 'Image 2',
                    'name' => 'mass_times_image_2',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65b9475c0ad1z',
                    'label' => 'Parish Name',
                    'name' => 'parish_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '*Max 35 characters',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '35',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_61a917aeb95ey',
                    'label' => 'Buttons',
                    'name' => 'mass_times_buttons',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 2,
                    'collapsed' => '',
                    'button_label' => 'Add Button',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_65b947840ad16',
                            'label' => 'Button',
                            'name' => 'mass_times_link',
                            'aria-label' => '',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'parent_repeater' => 'field_61a917aeb95ey',
                        ),
                    ),
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65cfaddc22530',
                    'label' => 'Content Type',
                    'name' => 'mass_times_content_type',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '*Choose if you want to display a free text area or your mass times',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => 'Mass Times',
                    'ui_off_text' => 'Textarea',
                    'ui' => 1,
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65cfae7e22531',
                    'label' => 'Content',
                    'name' => 'mass_times_content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_65cfaddc22530',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_61a917aeb95eb',
                    'label' => 'Sections',
                    'name' => 'mass_times_sections',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_65cfaddc22530',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'row',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'field_65cbaaf060971',
                    'button_label' => 'Add Day',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_65cbaaf060971',
                            'label' => 'Title',
                            'name' => 'title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '*Max. 50 characters',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_65cfaddc22530',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => 50,
                            'placeholder' => 'Weekends/Weekdays/Reconciliation',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_61a917aeb95eb',
                        ),
                        array(
                            'key' => 'field_65cbab5460972',
                            'label' => 'Times',
                            'name' => 'times',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '*Max. 4 times',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_65cfaddc22530',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'min' => 1,
                            'max' => 4,
                            'collapsed' => 'field_65cbaba160973',
                            'button_label' => 'Add Time',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_65cbaba160973',
                                    'label' => 'Day',
                                    'name' => 'day',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => 'Monday',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab5460972',
                                ),
                                array(
                                    'key' => 'field_65cbabe160974',
                                    'label' => 'Times',
                                    'name' => 'day_times',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '5:15 pm',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab5460972',
                                ),
                                array(
                                    'key' => 'field_65cbac2460975',
                                    'label' => 'Languages',
                                    'name' => 'languages',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '*optional',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => 'española',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab5460972',
                                ),
                                array(
                                    'key' => 'field_65cbac6a60976',
                                    'label' => 'Additional Notes',
                                    'name' => 'additional_notes',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '*optional',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => 'or by appointment',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab5460972',
                                ),
                            ),
                            'parent_repeater' => 'field_61a917aeb95eb',
                        ),
                    ),
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
            ),
        ),
        // array(
        //     'key' => 'field_65b94794b4ef8',
        //     'label' => 'Mass Times',
        //     'name' => '',
        //     'aria-label' => '',
        //     'type' => 'message',
        //     'instructions' => '',
        //     'required' => 0,
        //     'conditional_logic' => array(
        //         array(
        //             array(
        //                 'field' => 'field_65cfaddc22530',
        //                 'operator' => '==',
        //                 'value' => '1',
        //             ),
        //         ),
        //     ),
        //     'wrapper' => array(
        //         'width' => '33',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'message' => 'Edit mass times <a href="/wp-admin/admin.php?page=theme-general-settings">here</a>',
        //     'new_lines' => 'wpautop',
        //     'esc_html' => 0,
        // ),
    );
}
