<?php

function acf_welcome()
{
    return  array(
        array(
            'key' => 'field_65b80cc7c3c21',
            'label' => 'Welcome',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_65b8190295e1d',
            'label' => 'Show this section?',
            'name' => 'show_welcome',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui_on_text' => 'Yes',
            'ui_off_text' => 'No',
            'ui' => 1,
        ),
        array(
            'key' => 'field_65b80d37c3c23',
            'label' => 'Line 1',
            'name' => 'welcome_line_1',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*Max 80 characters',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65b8190295e1d',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => 80,
            'placeholder' => 'Welcome to St. Alphonsus',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_65b80d7dc3c24',
            'label' => 'Line 2',
            'name' => 'welcome_line_2',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*Max 80 characters',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65b8190295e1d',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => 80,
            'placeholder' => 'We are one body, one body in Christ.',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_65b80db0c3c25',
            'label' => 'Text color',
            'name' => 'welcome_text_color',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65b8190295e1d',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'var(--clr-primary)' => 'Primary',
                'var(--clr-secondary)' => 'Secondary',
                'var(--clr-tertiary)' => 'Tertiary',
                'var(--clr-quaternary)' => 'Quaternary',
                'black' => 'Black',
                'white' => 'White',
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 1,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_65b80d07c3c22',
            'label' => 'Overlay',
            'name' => 'welcome_overlay_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65b8190295e1d',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'enable_opacity' => 1,
            'return_format' => 'string',
        ),
        array(
            'key' => 'field_65b80e08c3c26',
            'label' => 'Background Image',
            'name' => 'welcome_background_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65b8190295e1d',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
        ),
    );
}
