<?php

acf_add_local_field_group(array(
    'key' => 'group_619f9dd6d382b',
    'title' => 'Footer Settings',
    'fields' => array(
        array(
            'key' => 'field_619f9f300e852',
            'label' => 'Footer Logo',
            'name' => 'footer_logo',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_6196abe21fgdrftg',
            'label' => 'Logo Link',
            'name' => 'footer_logo_link',
            'type' => 'link',
            'instructions' => '*Put a link on the image (optional)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_619fa3bbb3b64',
            'label' => 'Content',
            'name' => 'footer_content',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'rows' => 4,
            'placeholder' => '',
            'new_lines' => '',
        ),
        array(
            'key' => 'field_6196abe21fgdrftz',
            'label' => 'Button (Optional)',
            'name' => 'footer_button',
            'type' => 'link',
            'instructions' => '*Placed below footer content',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_626817e020a5f',
            'label' => 'Quicklinks',
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Edit the links at the bottom of the footer <a href="/wp-admin/nav-menus.php?action=edit&menu=17">here</a>.',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_65dcd8821445b',
            'label' => 'Quicklinks Header',
            'name' => 'footer_quicklinks_header',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*Max. 20 characters',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => 20,
            'placeholder' => 'Links',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_65d374f7b57ab',
            'label' => 'Contact Header',
            'name' => 'footer_contact_header',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*Max. 20 characters',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => 20,
            'placeholder' => 'Get In Touch',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_6196abe21fgdrfty',
            'label' => 'Donate Link',
            'name' => 'donate_link',
            'type' => 'link',
            'instructions' => '*Put a link on the donate image (optional). Default links to https://appeal.archdioceseofhartford.org/donations/',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-footer-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));