<?php
acf_add_local_field_group( array(
	'key' => 'group_6194526d98d09',
	'title' => 'Header Settings',
	'fields' => array(
		array(
			'key' => 'field_65b27e8ee1f78',
			'label' => 'Logos',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6194528cb817a',
			'label' => 'Header Logo',
			'name' => 'header_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '*Set the Logo next to the Navbar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_619452a2b817b',
			'label' => 'Header Logo (sticky)',
			'name' => 'header_logo_sticky',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '*Set the Header Logo for a sticky header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_65b27eaa735e2',
			'label' => 'Page Header',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_619452e8b817c',
			'label' => 'Default Featured Image',
			'name' => 'default_featured_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '*Set a placeholder featured image',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_660ae641e0ca2',
			'label' => 'Default Featured Image for Posts',
			'name' => 'default_post_featured_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '*Set a featured image for posts (optional, if not set the default featured image will be used)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_61a796d85eb3c',
			'label' => 'Page Header Overlay',
			'name' => 'page_header_overlay',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '* set the opacity of the overlay for the page header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				0 => 'none',
				'.125' => 'very light',
				'.25' => 'light',
				'.5' => 'normal',
				'.75' => 'heavy',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 1,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_65f4602580032',
			'label' => 'Show Breadcrumbs',
			'name' => 'show_breadcrumbs',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '* show/hide breadcrumbs below the page header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
			'ui' => 1,
		),
		array(
			'key' => 'field_6196abe21f65z',
			'label' => 'Custom Logo Link',
			'name' => 'logo_link',
			'type' => 'link',
			'instructions' => 'Filling this out will override the default logo link to the homepage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_65b27ebbced33',
			'label' => 'Top Bar',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_65b27ef9b0a3c',
			'label' => 'Show Address',
			'name' => 'top_bar_show_address',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Yes',
			'ui_off_text' => 'No',
			'ui' => 1,
		),
		array(
			'key' => 'field_65b27f2db0a3d',
			'label' => 'Show Email',
			'name' => 'top_bar_show_email',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_65b27f45b0a3e',
			'label' => 'Show Phone Number',
			'name' => 'top_bar_show_phone_number',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_65b27f5fb0a3f',
			'label' => 'Show Language Selector',
			'name' => 'show_language_selector',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '* requires GTranslate',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-header-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Set values for the site’s header.',
	'show_in_rest' => 0,
) );
