<?php

acf_add_local_field_group(array(
    'key' => 'group_620521faac5ab',
    'title' => 'Ministries Page',
    'fields' => array(
        array(
            'key' => 'field_620522099ad2e',
            'label' => 'Ministry Page Style',
            'name' => 'ministry_is_slider',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => 'Choose whether the ministries overview page is a static funnel or interactive sliders',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => 'Slider',
            'ui_off_text' => 'Funnel',
        ),
        array(
            'key' => 'field_65d4fbb0df558',
            'label' => 'Open Lightbox',
            'name' => 'open_lightbox',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '*Opens Lightbox on click on a ministry, that shows an excerpt and an optional contact form.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'ui' => 1,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'templates/page-ministries.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'side',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Ministry Overview Page Style (Funnel/Slider)',
    'show_in_rest' => 0,
    'display_title' => '',
    'allow_ai_access' => false,
    'ai_description' => '',
));
