<?php

acf_add_local_field_group(array(
    'key' => 'group_66db1ae6a0221',
    'title' => 'Post Category',
    'fields' => array(
        array(
            'key' => 'field_66db1ae7f6065',
            'label' => 'Single Article Title',
            'name' => 'single_article_title',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'the_title' => 'Post Title',
                'news-article' => 'News Article',
                'event' => 'Event',
                'blogpost' => 'Blog Post',
            ),
            'default_value' => false,
            'return_format' => 'label',
            'multiple' => 0,
            'allow_null' => 0,
            'allow_in_bindings' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_69cbf0cdee165',
            'label' => 'Header Image',
            'name' => 'header_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '*Set an image for the page header if you want it to be different from the site\'s default featured image',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'allow_in_bindings' => 0,
            'preview_size' => 'medium',
        ),

    ),
    'location' => array(
        array(
            array(
                'param' => 'taxonomy',
                'operator' => '==',
                'value' => 'category',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));